run:
  concurrency: 4
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: "1.23.4"
output:
  # format is the output format - same as that of golangci-lint
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
issues:
  exclude-use-default: false
  exclude:
    - "^.*SA1019.*$" # Excluding SA1019 errors
linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
  errcheck:
    check-type-assertions: true
  gosec:
    exclude-generated: false
    excludes:
      - G107
      - G204
      - G301
      - G304
      - G306
      - G307
      - G115 # https://github.com/securego/gosec/issues/1185
    severity: low
    confidence: low
