version: 2
before:
  hooks:
    - go mod download

builds:
  - id: "roller-darwin"
    main: ./
    binary: roller
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -X github.com/dymensionxyz/roller/version.BuildVersion={{.Version}}
      - -X github.com/dymensionxyz/roller/version.BuildCommit={{.Commit}}
      - -X github.com/dymensionxyz/roller/version.BuildTime={{.Date}}
  - id: "roller-darwin-arm64"
    main: ./
    binary: roller
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -X github.com/dymensionxyz/roller/version.BuildVersion={{.Version}}
      - -X github.com/dymensionxyz/roller/version.BuildCommit={{.Commit}}
      - -X github.com/dymensionxyz/roller/version.BuildTime={{.Date}}
  - id: "roller-linux"
    main: ./
    binary: roller
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -X github.com/dymensionxyz/roller/version.BuildVersion={{.Version}}
      - -X github.com/dymensionxyz/roller/version.BuildCommit={{.Commit}}
      - -X github.com/dymensionxyz/roller/version.BuildTime={{.Date}}
  - id: "roller-linux-arm64"
    main: ./
    binary: roller
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -X github.com/dymensionxyz/roller/version.BuildVersion={{.Version}} -X github.com/dymensionxyz/roller/version.BuildCommit={{.Commit}} -X github.com/dymensionxyz/roller/version.BuildTime={{.Date}}
  - id: "roller-windows"
    main: ./
    binary: roller
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags:
      - -X github.com/dymensionxyz/roller/version.BuildVersion={{.Version}}
      - -X github.com/dymensionxyz/roller/version.BuildCommit={{.Commit}}
      - -X github.com/dymensionxyz/roller/version.BuildTime={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}_{{- title .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - roller-darwin
      - roller-darwin-arm64
      - roller-windows
      - roller-linux
      - roller-linux-arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
snapshot:
  name_template: "{{ .Tag }}-next"
