global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
    log-level: info
    ics20-memo-limit: 0
    max-receiver-size: 150
chains:
    dymension_2018-1:
        type: cosmos
        value:
            key-directory: relayer/keys/dymension_2018-1
            key: relayer-hub-key
            chain-id: dymension_2018-1
            http-addr: ""
            is-dym-rollapp: false
            trust-period: 0s
            rpc-addr: http://rpc-dymension-pg.mzonder.com:36657
            account-prefix: dym
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 2000000000adym
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 10s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs:
                - ethermint
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    starlink_10579-1:
        type: cosmos
        value:
            key-directory: relayer/keys/starlink_10579-1
            key: relayer-rollapp-key
            chain-id: starlink_10579-1
            http-addr: ""
            is-dym-rollapp: false
            trust-period: 0s
            rpc-addr: https://rpc.six.evm.ra.pg.noisnemyd.xyz:443
            account-prefix: star
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: "2000000000"
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 10s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs:
                - ethermint
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths: {}
