name: Bug Report
description: File a bug report to inform the community on your awesome finding!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report!
  - type: input
    id: version
    attributes:
      label: Roller version
      description: >
        use 'roller version'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Environment
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. from /etc/os-release
    validations:
      required: true
  - type: input
    id: architecture
    attributes:
      label: Processor Architecture
      description: e.g. uname -m
    validations:
      required: true
  - type: textarea
    id: others
    attributes:
      label: Others
      description: >
        e.g. resources limitation(like cpu, ram limit, swap etc.)
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce it
      description: What steps have you made to reproduce it?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected result
      description: What do you expect to happen as a final result?
      placeholder: Let us know what is expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What do you see happened instead as a final result?
      placeholder: >
        This is the crucial part in detecting the root cause of the issue
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log(max 20 lines) output. This will
        be automatically formatted into code, so no need for backticks. Or paste
        gists, pastebins links here
      render: Shell
  - type: textarea
    id: misc
    attributes:
      label: Notes
      description: Is there anything else we need to know?
      placeholder: >
        Maybe, you have other ways to repro or what side effects there are if
        changing steps
