name: Feature Request
description: >
  Request a new feature to inform the community on what will be beneficial for
  the project!
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time and creating a new feature request!
  - type: textarea
    id: ideas
    attributes:
      label: Implementation ideas
      description: What ideas do you have on how to implement this?
