{
 "title": "Rollapp Infrastructure Metrics Roller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(up, instance)" } },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sequencer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "result" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "dymint_mempool_size{instance=\"${node}:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed DA Submissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "rollapp_consecutive_failed_da_submissions{instance=\"${node}:2112\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rollapp Hub Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "rollapp_hub_height{instance=\"${node}:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Message ( when status is Down )",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "result" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollapp_height{instance=\"${node}:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Batches Skew",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "rollapp_pending_submissions_skew_num_batches{instance=\"${node}:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height over time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "rollapp_height{instance=\"${node}:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Batches Skew Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "rollapp_pending_submissions_skew_num_bytes{instance=\"${node}:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size Tx/Block",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "irate(rollapp_block_size_txs{instance=\"${node}:2112\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}