name: Linters
on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
jobs:
  markdownlint:
    runs-on: ["self-hosted"]
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config-file: .markdownlint.yaml
